token: "XXXXXXXXXXXXXXXXXXX"  # Lichess OAuth2 Token.

engines:
  standard:
    dir: "./engines"
    name: "stockfish"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 11.8
    uci_options:
      Threads: 4 #hg
      Hash: 4096
      Move Overhead: 250
    limits:
      # time: 20.0
      # depth: 50
      # nodes: 8000000
  0.5+0:
    dir: "./engines"
    name: "stockfish"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 19.0
    uci_options:
      Threads: 4
      Hash: 4096
      Move Overhead: 108
    limits:
#      time: 20.0
#      depth: 50
#      nodes: 5000000
  bullet:
    dir: "./engines"
    name: "stockfish"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 12.0
    uci_options:
       Threads: 4
       Hash: 4096
       Move Overhead: 150
    limits:
#      time: 20.0
#      depth: 50
#      nodes: 5000000
    
  chess960:
    dir: "./engines"
    name: "stockfish"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 5.8
    uci_options:
       Threads: 4
       Hash: 4096
       Move Overhead: 169
    limits:
#      time: 20.0
#      depth: 50
#      nodes: 5000000


syzygy:
  standard:
    enabled: false
    paths:
      - "./engines/syzygy"
    max_pieces: 6
    instant_play: true
  antichess:
    enabled: false
    paths:
      - "/path/to/antichess/syzygy"
    max_pieces: 6
    instant_play: true
  atomic:
    enabled: false
    paths:
      - "/path/to/atomic/syzygy"
    max_pieces: 6
    instant_play: true

gaviota:
  enabled: false
  paths:
    - "/path/to/gaviota"
  max_pieces: 5

opening_books:
  enabled: true
  priority: 999
  books:
    standard_white:
      selection: best_move 
      allow_repetitions: true   
     # max_depth: 80
      names:
        - white
        - draw
    standard_black:
      selection: best_move 
      allow_repetitions: true   
     # max depth : 45 
      names:
        - black
        - draw
    standard_human: 
      selection: best_move 
      allow_repetitions: true 
      max depth : 1 
      names: 
        - draw
    standard_black_tournament:
      selection: best_move
      allow_repetitions: true   
      names:
        - black
        - draw
    standard_white_tournament:
      selection: best_move
      allow_repetitions: true   
      names: 
        - white
        - draw
    0.5+0_black:
      selection: best_move
      allow_repetitions: true   
      names: 
        - black
        - draw
        
online_moves:
  opening_explorer:
    enabled: false
    priority: 300
 #   player: Username
    only_without_book: false
    use_for_variants: true
    allow_repetitions: false              # Whether the cloud can create repetitions on the board. Can lead to unintentional draws.     
    min_time: 20
    timeout: 5
    min_games: 10
    only_with_wins: true
    selection: "performance"
    anti: true
    # max_depth: 20
  lichess_cloud:
    enabled: false
    priority: 200
    only_without_book: true
    min_eval_depth: 20
    min_time: 10
    timeout: 3
    use_for_variants: false
    allow_repetitions: true              # Whether the cloud can create repetitions on the board. Can lead to unintentional draws.
    trust_eval: true
    # max_depth: 30
  chessdb:
    enabled: false
    priority: 250
    only_without_book: false
    allow_repetitions: false              # Whether the chessdb can create repetitions on the board. Can lead to unintentional draws.
    trust_eval: true                     # Whether the chessdb eval should be trusted for draw offers and resignations.
    min_time: 10                       
    timeout: 3             
    best_move: true          
  online_egtb:
    enabled: true
    min_time: 5
    timeout: 3

offer_draw:
  enabled: true
  score: 10
  consecutive_moves: 2
  min_game_length: 30
  against_humans: false
 # min_rating: 3000

resign:
  enabled: true
  score: -1200
  consecutive_moves: 6
  against_humans: false
  min_rating: 3000

challenge:                                # Incoming challenges.
  concurrency: 3                          # Number of games to play simultaneously.
  max_takebacks: 3                        # Maximum number of takebacks granted to a human.
  bullet_with_increment_only: false       # Whether bullet games against BOTs should only be accepted with increment.
# min_increment: 0                        # Minimum amount of increment to accept a challenge.
# max_increment: 180                      # Maximum amount of increment to accept a challenge.
# min_initial: 0                          # Minimum amount of initial time to accept a challenge.
# max_initial: 315360000                  # Maximum amount of initial time to accept a challenge.
  variants:                               # Chess variants to accept (https://lichess.org/variant).
    - standard
    - chess960
#   - fromPosition
#   - antichess
#   - atomic
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
  bot_time_controls:                      # Speeds or time controls in initial_minutes+increment_seconds format to accept against BOTs.
    - bullet
    - blitz
#   - rapid
#   - classical
#   - 25+0
  human_time_controls:                    # Speeds or time controls in initial_minutes+increment_seconds format to accept against humans.
    - bullet
#   - blitz
#   - rapid
#   - classical
  bot_modes:                              # Game modes to accept against BOTs.
    - casual                              # Unrated games.
#   - rated                               # Rated games
  human_modes:                            # Game modes to accept against humans.
    - casual                              # Unrated games.
#   - rated                               # Rated games

matchmaking:
  delay: 60                               # Time in seconds the bot must be idle before a new challenge is started.
  timeout: 60                             # Time until a challenge is canceled.
  selection: cyclic                       # Matchmkaing type selection is one of "weighted_random", "sequential" or "cyclic".
  types:                                  # Matchmaking types of which one is selected before each game.
    hyperbullet:                          # Arbitrary name of the matchmaking type. Names must be unique.
      tc: 0.5+0                           # Time control in initial_minutes+increment_seconds format.
      rated: false                        # Whether matchmaking should play rated games. Default: true
    slowhyperbullet:                      # Arbitrary name of the matchmaking type. Names must be unique.
      tc: 0.5+1                           # Time control in initial_minutes+increment_seconds format.
      rated: false                        # Whether matchmaking should play rated games. Default: true
    fastbullet:                           # Arbitrary name of the matchmaking type. Names must be unique.
      tc: 1+0                             # Time control in initial_minutes+increment_seconds format.
      rated: false                        # Whether matchmaking should play rated games. Default: true
    bullet:                               # Arbitrary name of the matchmaking type. Names must be unique.
      tc: 1+1                             # Time control in initial_minutes+increment_seconds format.
      rated: false                        # Whether matchmaking should play rated games. Default: true
    slowbullet:                           # Arbitrary name of the matchmaking type. Names must be unique.
      tc: 2+0                             # Time control in initial_minutes+increment_seconds format.
      rated: false                        # Whether matchmaking should play rated games. Default: true
    slowerbullet:                         # Arbitrary name of the matchmaking type. Names must be unique.
      tc: 2+1                             # Time control in initial_minutes+increment_seconds format.
      rated: false                        # Whether matchmaking should play rated games. Default: true

messages:
  greeting: "Hello {opponent}! Good luck and have fun! Type !help for a list of commands."
  goodbye: "Thank you for the game, {opponent}!"
  greeting_spectators: "Welcome spectators! Type !help for a list of commands."
  goodbye_spectators: "Thank you all for watching!"

whitelist:
#
blacklist:
#
online_blacklists:
#
books:
  draw: "./books/draw.bin"
  white: "./books/white.bin"
  black: "./books/black.bin"
