name: Run bot

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "user_interface.py"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 355  # just under 6h limit

    concurrency:
      group: bot-run
      cancel-in-progress: false  # keep live jobs safe

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Cache pip downloads
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Query latest Stockfish dev release asset URL
        id: get_url
        run: |
          url=$(curl -s https://api.github.com/repos/official-stockfish/Stockfish/releases \
            | jq -r '[.[] | select(.prerelease==true and (.tag_name|type == "string") and (.tag_name|test("^stockfish-dev")))] | .[0].assets[] | select(.name|test("stockfish-ubuntu-x86-64-bmi2.tar$")).browser_download_url')
          echo "ASSET_URL=$url" >> $GITHUB_ENV

      - name: Download and extract Stockfish
        run: |
          curl -L "$ASSET_URL" -o stockfish.tar
          tar -xf stockfish.tar

      - name: Move and rename Stockfish binary to 'engines/stockfish'
        run: |
          mkdir -p engines
          mv stockfish/stockfish-ubuntu-x86-64-bmi2 engines/stockfish

      - name: Clean up
        run: rm -rf stockfish stockfish.tar

      - name: Install dependencies & prepare
        run: |
          pip install --no-cache-dir --prefer-binary -r requirements.txt
          sed -i "s/XXXXXXXXXXXXXXXXXXX/${{ secrets.TOKEN }}/g" config.yml
          chmod +x ./engines/stockfish ./engines/fairy-stockfish_x86-64-bmi2 ./engines/stockfish-7-x64-bmi2

      - name: Run Bot
        run: |
          echo "Starting bot..."
          python3 -u user_interface.py matchmaking &
          PID=$!
          # Auto-exit before GitHub 6h limit
          ( sleep 20700 && echo "Time up. Killing bot..." && kill -SIGTERM $PID ) &
          wait $PID
          echo "Bot ended cleanly."

      - name: 🔁 Self-Restart
        run: gh workflow run "Run bot"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}




