name: Sync BotLi Python Files

on:
  workflow_dispatch:  # Run manually only

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone BotLi
        run: |
          git clone --depth 1 https://github.com/Torom/BotLi temp_BotLi

      - name: Sync .py files to main
        run: |
          git checkout main
          rsync -av --include='*/' --include='*.py' --exclude='*' temp_BotLi/ ./
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -u
          git add *.py || true
          git commit -m "Sync .py files from Torom/BotLi [main]" || echo "No changes to commit"
          git pull --rebase origin main || true
          git push origin main

      - name: Sync .py files to Tournament
        run: |
          git checkout Tournament
          rsync -av --include='*/' --include='*.py' --exclude='*' temp_BotLi/ ./
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -u
          git add *.py || true
          git commit -m "Sync .py files from Torom/BotLi [Tournament]" || echo "No changes to commit"
          git pull --rebase origin Tournament || true
          git push origin Tournament
